general:
  mail_smtp_server: "smtp.example.com:587"
  mail_auth_user: "alice@example.com"
  mail_auth_password: "alice_password"
  mail_address_from: "bob@example.com"
  mailing_list:
    - "carol@example.com"
    - "dave@example.com"

services_list:
  - process_name: "service1.py"
    description: ""
    disabled: false
    start_cmd: "python3 service1.py"
    cmd_args:
      - "--firstArg=01"
      - "--SecondArg 02"
    stop_cmd: "pkill -f service1.py"
    python_venv: "/opt/python/venv/service1"
    working_directory: "/tmp/"
    pid_file: "service1.pid"
    env_vars:
      - "FIRST_SOME_VAR='Some value'"
      - "second_some_var=42"
      - "THIRD_Var=Third value"
    mailing_list:
      - "carol@example.com"

  - process_name: "service2.py"
    start_cmd: "/usr/bin/tail -f /tmp/service2.py"

  - process_name: "service3.sh"
    description: ""
    disabled: true
    start_cmd: "./service3.sh"
    pid_file: ""
    working_directory: "/tmp/"

  - process_name: ""
    description: "broken service without name"
    disabled: true
