name: Release tags

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build, test, upload assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Collect release metadata
        id: release_meta
        run: |
          release_tag=$(basename "${{ github.ref }}")
          release_date=$(date -u '+%F')
          release_name="${release_date} / ${release_tag}"
          echo "release_meta_release_tag=${release_tag}" >> "$GITHUB_ENV"
          echo "release_meta_release_name=${release_name}" >> "$GITHUB_ENV"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'

      - name: Build
        run: make

      - name: Check version
        run: |
          ./autosys-nanny --version

      - name: Create archive with binary
        run: tar -cvzf autosys-nanny-${{ env.release_meta_release_tag }}-linux-amd64.tar.gz autosys-nanny

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: autosys-nanny-${{ env.release_meta_release_tag }}-linux-amd64.tar.gz

  release:
    name: Create GitHub release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Collect release metadata
        id: release_meta
        run: |
          release_tag=$(basename "${{ github.ref }}")
          release_date=$(date -u '+%F')
          release_name="${release_date} / ${release_tag}"
          echo "release_meta_release_tag=${release_tag}" >> "$GITHUB_ENV"
          echo "release_meta_release_name=${release_name}" >> "$GITHUB_ENV"

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "autosys-nanny-${{ env.release_meta_release_tag }}-linux-amd64.tar.gz"
          tag: ${{ env.release_meta_release_tag }}
          name: ${{ env.release_meta_release_name }}
          allowUpdates: true
          draft: false
          makeLatest: true
          prerelease: false
          replacesArtifacts: true
